USE transport_company;
CREATE TABLE IF NOT EXISTS `Груз` (
  `idГруз` INT NOT NULL,
  `TIP GRUZA` NVARCHAR(85) NOT NULL,
  `TONNAZh GRUZA`NVARCHAR(45) NOT NULL,
  `MARShRUT`NVARCHAR(125) NOT NULL,
  `DATA ZAKAZA` datetime NOT NULL,
 
  PRIMARY KEY (`idГруз`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Transport` (
  `idTransport` INT UNSIGNED ZEROFILL NOT NULL,
  `TONNAZh`NVARCHAR(45) NOT NULL,
  `MARKA`NVARCHAR(45) NOT NULL,
  `GABARITY`NVARCHAR(45) NOT NULL,
  `GOSNOMER`NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransport`),
  UNIQUE INDEX `idTransport_UNIQUE` (`idTransport` ASC) VISIBLE)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Voditel` (
  `idVoditel` INT NOT NULL,
  `FIO`NVARCHAR(125) NOT NULL,
  `NOMER VODITELSKIKh PRAV`NVARCHAR(45) NOT NULL,
  `KATEGORIYa`NVARCHAR(45) NOT NULL,
  `Strakhovoi polis`NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVoditel`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Klienty` (
  `idtable1` INT NOT NULL,
  ` FIO` NVARCHAR(120) NOT NULL,
  `MESTO NAZNAChENIYa`NVARCHAR(120) NOT NULL,
  `NAZVANIE GRUZA`NVARCHAR(45) NOT NULL,
  `GABARITY GRUZA`NVARCHAR(45) NOT NULL,
  `TELEFON` VARCHAR(12) NOT NULL,
  `ADRES DOSTAVKI`NVARCHAR(88) NOT NULL,
  `ADRES OTPRAVKI`NVARCHAR(88) NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ZAKAZY` (
  `idZAKAZY`  INT NOT NULL,
  `Transport_idTransport` INT UNSIGNED ZEROFILL NOT NULL,
  `Voditel_idVoditel` INT NOT NULL,
  `Klienty_idtable1` INT NOT NULL,
  `Груз_idГруз` INT NOT NULL,
  PRIMARY KEY (`idZAKAZY`, `Transport_idTransport`, `Voditel_idVoditel`, `Klienty_idtable1`, `Груз_idГруз`),
  INDEX `fk_ZAKAZY_Transport1_idx` (`Transport_idTransport` ASC) VISIBLE,
  INDEX `fk_ZAKAZY_Voditel1_idx` (`Voditel_idVoditel` ASC) VISIBLE,
  INDEX `fk_ZAKAZY_Klienty1_idx` (`Klienty_idtable1` ASC) VISIBLE,
  INDEX `fk_ZAKAZY_Груз1_idx` (`Груз_idГруз` ASC) VISIBLE,
  CONSTRAINT `fk_ZAKAZY_Transport1`
    FOREIGN KEY (`Transport_idTransport`)
    REFERENCES `Transport` (`idTransport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZAKAZY_Voditel1`
    FOREIGN KEY (`Voditel_idVoditel`)
    REFERENCES `Voditel` (`idVoditel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZAKAZY_Klienty1`
    FOREIGN KEY (`Klienty_idtable1`)
    REFERENCES `Klienty` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZAKAZY_Груз1`
    FOREIGN KEY (`Груз_idГруз`)
    REFERENCES `Груз` (`idГруз`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

